// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLN-L82XSAsRVO-tbBLIhbfxzs-9W1rQ',
    appId: '1:521627758022:web:9c582fd2774756b2b596c7',
    messagingSenderId: '521627758022',
    projectId: 'vichaar-31878',
    authDomain: 'vichaar-31878.firebaseapp.com',
    storageBucket: 'vichaar-31878.appspot.com',
    measurementId: 'G-BLJFJ9YLZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrdZtBSaHZ3Vw47B2q7PNrEsHt4I023zY',
    appId: '1:521627758022:android:01211acddd866d80b596c7',
    messagingSenderId: '521627758022',
    projectId: 'vichaar-31878',
    storageBucket: 'vichaar-31878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJF_sndIbBGEtmQlRYlXSWQ6DPPkj-sPM',
    appId: '1:521627758022:ios:d7dc65915878f4a1b596c7',
    messagingSenderId: '521627758022',
    projectId: 'vichaar-31878',
    storageBucket: 'vichaar-31878.appspot.com',
    iosBundleId: 'com.example.vichaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJF_sndIbBGEtmQlRYlXSWQ6DPPkj-sPM',
    appId: '1:521627758022:ios:d7dc65915878f4a1b596c7',
    messagingSenderId: '521627758022',
    projectId: 'vichaar-31878',
    storageBucket: 'vichaar-31878.appspot.com',
    iosBundleId: 'com.example.vichaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdLN-L82XSAsRVO-tbBLIhbfxzs-9W1rQ',
    appId: '1:521627758022:web:56d3c53d20452d48b596c7',
    messagingSenderId: '521627758022',
    projectId: 'vichaar-31878',
    authDomain: 'vichaar-31878.firebaseapp.com',
    storageBucket: 'vichaar-31878.appspot.com',
    measurementId: 'G-G7Y5G27SBL',
  );
}
